### ISSUE TITLE
Can I write the fan speed?

### ISSUE THREAD

**Issue by xLexip** [lostcontrol/esphome-helios-kwl#1]
Hey,

thanks for sharing this. Can I also set the fan speed from homeassistant with this? Since you can do it with the Helios control panel I guess you can, but it is not shown on the screenshots.

**Comment by xLexip** [comment]
Yes, you can. Looked at the code.

**Comment by lostcontrol** [comment]
Hi. Yes you can. The switch that you see on the screenshot to turn the fan on/off also allows you set set the different speeds.

**Comment by Sadel3001** [comment]
how does this work? Where do I have to click?

**Comment by lostcontrol** [comment]
> how does this work? Where do I have to click?

Click on this: 

![Image](https://github.com/user-attachments/assets/06e1601e-37d8-4a71-a8ba-1569ef2cb692)
